/**
 * COCONUT V14 - PHASE 4 JOUR 3
 * Animations - Barrel Export
 * 
 * Export centralisé de toutes les animations
 */

// Transitions
export {
  TIMING,
  EASING,
  fadeTransition,
  fadeVariants,
  slideTransition,
  slideVariants,
  scaleTransition,
  scaleVariants,
  scaleUpVariants,
  collapseVariants,
  staggerContainer,
  staggerItem,
  staggerFadeSlide,
  spinnerVariants,
  pulseVariants,
  shimmerVariants,
  dotsContainer,
  dotVariants,
  successVariants,
  successBounce,
  errorShake,
  errorPulse,
  backdropVariants,
  modalContentVariants,
  drawerVariants,
  prefersReducedMotion,
  getAccessibleTransition,
  getAccessibleVariants,
} from './transitions';

// Variants
export {
  buttonHoverVariants,
  buttonGlowVariants,
  cardHoverVariants,
  cardRevealVariants,
  cardFlipVariants,
  imageZoomVariants,
  imageRevealVariants,
  inputFocusVariants,
  labelFloatVariants,
  badgeEntranceVariants,
  badgePulseVariants,
  iconSpinVariants,
  iconBounceVariants,
  iconWiggleVariants,
  toastVariants,
  toastSideVariants,
  progressFillVariants,
  skeletonShimmerVariants,
  dropdownVariants,
  menuItemsVariants,
  menuItemVariants,
  tabContentVariants,
  tabIndicatorVariants,
  scrollFadeVariants,
  scrollSlideVariants,
  glowPulseVariants,
  floatingVariants,
  particleVariants,
  cocoBoardCardVariants,
  generationProgressVariants,
  resultRevealVariants,
} from './variants';

// Micro-interactions
export {
  hoverLift,
  hoverScaleUp,
  hoverGlow,
  hoverBrightness,
  hoverTilt,
  clickScaleDown,
  clickRippleVariants,
  clickBounce,
  focusRing,
  focusGlow,
  focusScale,
  dragConstraints,
  dragActive,
  dragElasticReturn,
  switchToggleVariants,
  checkboxCheckVariants,
  successPulse,
  warningPulse,
  copySuccessVariants,
  pasteFlash,
  loadingDotsContainer,
  loadingDot,
  loadingSpinner,
  loadingPulse,
  numberIncrementBounce,
  numberDecrementShake,
  badgePopIn,
  badgeAttentionPulse,
  tooltipFadeIn,
  popoverSpringOpen,
  skeletonShimmer,
  skeletonPulse,
  confettiParticle,
  successCelebration,
  creditPulse,
  assetCardReveal,
  promptEditorFocus,
  generationCompleteSparkle,
} from './micro-interactions';

// Re-export error shake from micro-interactions as well
export { errorShake as microErrorShake } from './micro-interactions';
