/**
 * COCONUT V14 - MOCK DATA SERVICE
 * 
 * Provides pre-generated 9/10 creative concepts for testing without consuming AI credits.
 * These are real concepts generated by our enhanced Creative Excellence system prompt.
 */

import type { VideoAnalysisResponse } from './coconut-v14-video-analyzer.ts';

// ============================================================================
// MOCK CONCEPTS (9/10 CREATIVITY LEVEL)
// ============================================================================

/**
 * CONCEPT 1: Orée - Roots of Concrete
 * Real concept generated on 2026-01-15
 * Metaphor: Nature dormant beneath urban architecture
 */
export const MOCK_OREE_ROOTS_CONCRETE: VideoAnalysisResponse = {
  projectTitle: "Orée - Roots of Concrete",
  concept: {
    narrative: "A surreal journey revealing that beneath the cold, grey veneer of the modern city lies a dormant, ancient forest waiting to be awakened. The perfume is not an accessory; it is the key that breaks the concrete illusion and releases the wild nature within.",
    storytelling: "Visual Metaphor: 'Nature Reclaiming the Artificial.' We move from sterile monochrome architecture to warm, organic, living wood textures that burst through the grey. The product is the catalyst for this transformation.",
    tone: "Enigmatic, visceral, organic, surreal. High-contrast aesthetics merging Brutalist architecture with macro botany.",
    cta: "Orée. Reclaim your nature. -9% in January."
  },
  timeline: {
    totalDuration: 30,
    totalShots: 5
  },
  shots: [
    {
      id: "shot-1",
      order: 1,
      duration: 6,
      startTime: 0,
      endTime: 6,
      type: "establishing",
      description: "A stark, brutalist concrete corridor where the floor begins to ripple and turn transparent, revealing massive, ancient tree roots moving underneath like leviathans.",
      veoPrompt: "[00:00-00:03] Low angle, vertical 9:16 tracking shot moving backward down a sterile, high-fashion brutalist concrete hallway. The lighting is cold, clinical, top-down LED strips. In the center, a solitary figure in a sharp structural coat walks away from the camera. [00:03-00:06] As the figure steps, the concrete floor beneath their feet ripples like liquid mercury, turning semi-transparent. Beneath the surface, we see deep, dark, ancient tree roots writhing and pulsing with a warm amber bioluminescence, contrasting sharply with the cold grey above. Style: Cinematic surrealism, shot on Arri Alexa 65, anamorphic lens, desaturated cool tones with isolated warm highlights.",
      generationType: "TEXT_2_VIDEO",
      imageUrls: [],
      aspectRatio: "9:16",
      sfx: "SFX: Heavy, echoing footsteps that morph into the deep creaking of old wood.",
      mood: "Mysterious, dystopian yet organic",
      style: "Sci-fi organic surrealism",
      transition: "match-cut",
      estimatedCost: 30
    },
    {
      id: "shot-2",
      order: 2,
      duration: 6,
      startTime: 6,
      endTime: 12,
      type: "close-up",
      description: "A hand touches a cold steel wall, and the contact point instantly transforms the metal into textured, living bark.",
      veoPrompt: "[00:00-00:03] Extreme close-up macro shot. A hand with an elegant, minimalist ring reaches out to touch a smooth, cold brushed steel surface. The lighting is moody, side-lit to emphasize texture. [00:03-00:06] The moment the fingertip makes contact, a shockwave of transformation ripples out. The steel bubbles and cracks, instantly morphing into rugged, deep brown pine bark. Golden sap bleeds from the cracks, glowing intensely. The transformation is visceral and rapid, like time-lapse decay and regrowth simultaneously. Focus stays sharp on the texture change. Style: Hyper-real textural cinematography, 100mm macro lens.",
      generationType: "TEXT_2_VIDEO",
      imageUrls: [],
      aspectRatio: "9:16",
      sfx: "SFX: The sound of ice cracking mixed with the wet tearing of fibrous wood.",
      mood: "Visceral, transformative",
      style: "Macro textural transformation",
      transition: "dissolve",
      estimatedCost: 30
    },
    {
      id: "shot-3",
      order: 3,
      duration: 6,
      startTime: 12,
      endTime: 18,
      type: "product-hero",
      description: "The Orée bottle emerges from a pool of liquid gold resin that defies gravity, solidifying into the glass form.",
      veoPrompt: "Vertical 9:16 shot. [00:00-00:03] In a pitch-black void, a pool of thick, golden amber resin sits at the bottom. Suddenly, droplets of the resin begin to fall UPWARDS, defying gravity. [00:03-00:06] The reverse-rain of amber swirls into the center of the frame, coalescing and hardening to form the Orée perfume bottle. The bottle is identical to the reference image, with its sharp square edges and gold cap. The liquid resin becomes the solid glass and liquid scent inside. Lighting is dramatic rim lighting, highlighting the golden liquid and the bottle's silhouette. The bottle rotates slowly as it forms. Style: High-end CGI product reveal, luxurious and ethereal.",
      generationType: "REFERENCE_2_VIDEO",
      imageUrls: [],
      aspectRatio: "9:16",
      sfx: "SFX: Reverse water droplet sounds, a resonant glass 'hum' as the bottle forms.",
      mood: "Magical, premium",
      style: "Gravity-defying product sculpture",
      transition: "cross-dissolve",
      estimatedCost: 40
    },
    {
      id: "shot-4",
      order: 4,
      duration: 6,
      startTime: 18,
      endTime: 24,
      type: "medium",
      description: "The human subject stands in the city, but their shadow casts the shape of a dense, wild forest.",
      veoPrompt: "[00:00-00:03] Medium vertical shot. The enigmatic figure from Shot 1 stands still in the center of a modern, white minimalist plaza. The sun is harsh, creating a strong shadow. [00:03-00:06] We tilt down to the shadow cast on the white pavement. The shadow does not match the person; instead, it is the complex, intricate silhouette of a wild, ancient forest canopy blowing in the wind. The shadow is alive, moving independently of the static figure. A visual metaphor for the inner nature released by the scent. Style: Surrealist photography, high contrast black and white aesthetic with the figure in color.",
      generationType: "TEXT_2_VIDEO",
      imageUrls: [],
      aspectRatio: "9:16",
      sfx: "SFX: The roar of wind through trees, silencing the city traffic noise.",
      mood: "Psychological, profound",
      style: "Jungian shadow archetype",
      transition: "fade",
      estimatedCost: 30
    },
    {
      id: "shot-5",
      order: 5,
      duration: 6,
      startTime: 24,
      endTime: 30,
      type: "transition",
      description: "The bottle sits on a piece of raw charred wood in a misty void. Text overlay appears: 'ORÉE - JANVIER -9%'.",
      veoPrompt: "Vertical 9:16 product shot. The Orée perfume bottle (identical to reference) rests majestically on a slab of charred, black Yakisugi wood. The texture of the burned wood contrasts with the smooth glass and gold of the bottle. Soft, low-lying fog drifts across the surface. The lighting is moody and atmospheric, spotlighting the label 'Orée'. The camera slowly pushes in towards the bottle. This negative space above the bottle is left clear for text overlays. Atmosphere: Quiet confidence, raw elegance.",
      generationType: "REFERENCE_2_VIDEO",
      imageUrls: [],
      aspectRatio: "9:16",
      sfx: "SFX: A deep, final bass thud. A whisper saying 'Orée'.",
      mood: "Conclusive, elegant",
      style: "Still life fine art",
      transition: "fade",
      estimatedCost: 40
    }
  ],
  audio: {
    music: "Avant-garde electronic ambient. Starts with cold, industrial metallic drones, then introduces warm, organic wooden percussion (marimba, woodblocks) that takes over the rhythm. Tempo: Slow, deliberate, hypnotic.",
    narration: "(No voiceover, text only to maintain mystery)",
    sfx: [
      "Deep creaking wood",
      "Cracking ice/concrete",
      "Reverse liquid flow",
      "Wind through leaves",
      "Heartbeat bass thud"
    ]
  },
  postProduction: {
    colorGrading: "Dual-tone grade: Steel Blue (shadows) vs. Amber Gold (highlights). High contrast curve. Grain added for filmic texture.",
    transitions: [
      "Match-cut on movement",
      "Fluid morphs",
      "Fade to black"
    ],
    titling: [
      "Shot 5 Overlay: 'L'APPEL DE LA FORÊT'",
      "Shot 5 Overlay: 'JANVIER -9% SUR TOUT'"
    ]
  },
  estimatedCost: {
    analysis: 100,
    shotsGeneration: 170,
    total: 270
  }
};

/**
 * CONCEPT 2: Essence - Memory Extraction
 * Metaphor: Scent as captured memory in water droplet
 */
export const MOCK_ESSENCE_MEMORY: VideoAnalysisResponse = {
  projectTitle: "Essence - L'Extraction de Mémoire",
  concept: {
    narrative: "Instead of showing the perfume as luxury object, we explore the idea that olfactory sensations have an invisible architecture. We visualize scent as a geometric structure that builds in space, then collapses to reveal the bottle - as if the product contained the architectural blueprint of an emotion.",
    storytelling: "Journey from abstract to tangible: We start with a microscopic water droplet suspended in void, dive INTO it to discover fragmented memories, then watch as the droplet transforms into the perfume bottle itself.",
    tone: "Dreamlike, contemplative, mysterious with peaceful resolution. Emotion: Nostalgia transformed into present wonder.",
    cta: "Essence - Where memory begins"
  },
  timeline: {
    totalDuration: 30,
    totalShots: 5
  },
  shots: [
    {
      id: "shot-1",
      order: 1,
      duration: 6,
      startTime: 0,
      endTime: 6,
      type: "establishing",
      description: "Extreme macro of single water droplet suspended in pitch black void",
      veoPrompt: "[00:00-00:02] Extreme close-up in complete darkness. A single point of light appears - a perfect water droplet suspended motionless in pitch black void. Surface tension creates a mirror-like sphere catching invisible light sources from off-frame. [00:02-00:04] Slow dolly push toward the droplet. As we approach, prismatic refractions begin to appear inside - hints of green, gold, violet dancing within the liquid. [00:04-00:06] Camera continues pushing until the droplet surface fills entire frame. Through the curved lens of water, we glimpse fragmented, dreamlike shapes - petals, leaves, sunlight - like memories trapped in amber. SFX: Profound silence broken only by a single, resonant water drop sound (low frequency, almost sub-bass). Ambient noise: Distant, ethereal wind chimes. Lighting: Single point source creating dramatic rim light on droplet edge. Shot on Arri Alexa 65 with macro lens, shallow depth of field, high contrast with crushed blacks and luminous highlights. Color grading: Desaturated with selective color on prismatic refractions.",
      generationType: "TEXT_2_VIDEO",
      imageUrls: [],
      aspectRatio: "16:9",
      sfx: "Single resonant water drop (low frequency), distant ethereal wind chimes",
      mood: "Mysterious, contemplative, suspended in time",
      style: "Hyper-macro cinematographic, high contrast, deep black with prismatic light",
      transition: "match-cut",
      estimatedCost: 30
    },
    {
      id: "shot-2",
      order: 2,
      duration: 6,
      startTime: 6,
      endTime: 12,
      type: "transition",
      description: "POV dive INTO the droplet - entering fragmented memory realm",
      veoPrompt: "[00:00-00:02] POV shot. We dive THROUGH the surface of the water droplet with smooth, weightless camera movement. Surface ripples in slow motion as we pass through, creating concentric wave patterns. [00:02-00:04] Inside the droplet, we're in a prismatic realm. Light refracts into spectrum colors - everything is fragmented like kaleidoscope. Abstract shapes float past: petal silhouettes, leaf shadows, golden sunlight rays, all dissolving and reforming. [00:04-00:06] Fragments begin to coalesce. We glimpse brief, impressionistic flashes of childhood garden - swing set in motion blur, flowers in soft focus, dappled sunlight through leaves - but everything remains abstract and dreamlike, never fully forming. World inside droplet is memory in liquid form. SFX: Underwater acoustics (muffled, dreamlike), gentle bubbles rising, distant laughter of child (heavily processed, ghostly). Music: Ethereal piano notes begin, each note reverberating endlessly. Lighting: Caustic light patterns dancing across surfaces, prismatic rainbow refractions. Shot on Sony Venice with underwater housing and anamorphic lens. Color grading: Oversaturated within droplet world, bloom effect on highlights.",
      generationType: "TEXT_2_VIDEO",
      imageUrls: [],
      aspectRatio: "16:9",
      sfx: "Underwater acoustics, gentle bubbles, distant processed child laughter",
      mood: "Dreamlike, fluid, fragmented like a dream",
      style: "POV immersive, prismatic effects and caustics, anamorphic",
      transition: "cross-dissolve",
      estimatedCost: 30
    },
    {
      id: "shot-3",
      order: 3,
      duration: 6,
      startTime: 12,
      endTime: 18,
      type: "medium",
      description: "Abstract garden memory - shapes dissolve into vapor",
      veoPrompt: "[00:00-00:02] Wide shot. Abstract representation of garden, but not realistic - everything made of translucent, watercolor-like shapes. Flowers bloom in fast-motion, but they're made of light and water vapor rather than solid matter. Trees are vertical streams of emerald light. [00:02-00:04] Tracking shot moving through this memory garden. Childhood objects appear as ghostly silhouettes: wooden swing made of golden mist, watering can pouring light instead of water, footprints in grass that fill with glowing particles. Each element is beautiful but ephemeral. [00:04-00:06] Garden begins to dissolve. Flowers turn into vapor trails that rise toward camera. Leaves become spirals of emerald smoke. Entire scene deconstructs back into abstract light and mist, rising upward like reverse rain. SFX: Delicate wind through leaves (processed with reverb), soft footsteps on grass (distant, ghostly), flowers blooming (crystalline chime sounds). Music: Orchestral swell begins - strings and woodwinds creating nostalgic but modern soundscape. Lighting: Soft, diffused natural light filtered through vapor, creating volumetric god rays. Shot on Arri Alexa Mini with Lensbaby Velvet lens for dreamy soft-focus aesthetic. Color grading: Pastel palette - soft pinks, lavender, sage green, warm gold - with bloom effect on all light sources.",
      generationType: "TEXT_2_VIDEO",
      imageUrls: [],
      aspectRatio: "16:9",
      sfx: "Delicate wind, soft ghostly footsteps, crystalline bloom sounds",
      mood: "Nostalgic, ephemeral, bittersweet",
      style: "Abstract watercolor, volumetric lighting, dreamy soft-focus",
      transition: "fade",
      estimatedCost: 30
    },
    {
      id: "shot-4",
      order: 4,
      duration: 6,
      startTime: 18,
      endTime: 24,
      type: "product-hero",
      description: "Vapor materializes into perfume bottle - memory becomes tangible",
      veoPrompt: "[00:00-00:02] Medium shot. Rising vapor trails from dissolved garden converge in mid-air against dark, minimal background. Mist swirls and compresses, becoming denser and more defined, as if memory is condensing back into physical form. [00:02-00:04] From within swirling vapor, the Essence perfume bottle begins to materialize. It appears gradually, like sculpture emerging from fog - first outline, then glass catching light, finally golden cap. Bottle seems to be made FROM memory vapor itself. Liquid inside bottle glows softly, as if it contains captured light. [00:04-00:06] Vapor fully dissipates, revealing perfume bottle in perfect clarity. It rests on surface of polished dark stone with water ripples reflecting on it. Bottle is elegant but simple - magic is in how it appeared, not its luxury aesthetic. Final frame: Bottle centered, cap gleaming, with last wisps of vapor curling away. SFX: Vapor compression sound (whoosh building to silence), glass crystallizing (delicate, high-frequency chimes), final note - soft 'plink' as bottle settles. Music: Orchestral score reaches gentle climax, then holds on sustained, peaceful note. Lighting: Three-point lighting with soft key light, rim light creating glow around bottle edges, subtle backlight through vapor. Shot on RED Komodo with macro lens, deep focus to show every detail. Color grading: Return to naturalistic tones - warm amber for bottle, cool slate for stone, subtle mist glow.",
      generationType: "REFERENCE_2_VIDEO",
      imageUrls: [],
      aspectRatio: "16:9",
      sfx: "Vapor compression whoosh, glass crystallizing chimes, soft settling plink",
      mood: "Revelation, calm wonder, resolution",
      style: "Cinematic product hero with narrative approach, not advertising",
      transition: "cut",
      estimatedCost: 40
    },
    {
      id: "shot-5",
      order: 5,
      duration: 6,
      startTime: 24,
      endTime: 30,
      type: "close-up",
      description: "Call-to-action with poetic typography",
      veoPrompt: "[00:00-00:03] Extreme close-up on liquid inside bottle. We see it's not just clear perfume - microscopic particles of light swim within, like memory fragments from earlier. Liquid catches light, creating same prismatic refractions we saw inside original water droplet, completing visual metaphor circle. Camera slowly dollies out. [00:03-00:05] Pull back to reveal full bottle again, now with elegant typography appearing in space beside it - not as overlay but as if words are made of same mist: 'Essence' (larger), then below 'Où commence la mémoire' (smaller, delicate font). [00:05-00:06] Final wide shot. Bottle sits in darkness with just text glowing softly. Typography fades to leave only bottle with single point of light on its cap - like original droplet we started with. Full circle. SFX: Soft whisper of wind, final piano note (held and fading). Music: Score resolves to silence, leaving only breath-like ambient sound. Lighting: Dramatic single source, chiaroscuro aesthetic, bottle silhouette with glowing cap. Shot on Arri Alexa LF with anamorphic lens for cinematic aspect. Color grading: Return to high contrast - deep blacks with luminous highlights on bottle and text.",
      generationType: "REFERENCE_2_VIDEO",
      imageUrls: [],
      aspectRatio: "16:9",
      sfx: "Soft wind whisper, final held piano note fading to silence",
      mood: "Contemplative, complete, invitation without urgency",
      style: "Minimalist cinematic, typography integrated organically",
      transition: "fade",
      estimatedCost: 40
    }
  ],
  audio: {
    music: "Orchestral score with ethereal piano, soft strings, and nostalgic woodwinds. Emotional crescendo that resolves to contemplative silence. Style: Neo-classical minimalist (think Max Richter / Ólafur Arnalds)",
    sfx: [
      "Single water drop (sub-bass frequency)",
      "Underwater acoustics and bubbles",
      "Child laughter (processed, ghostly)",
      "Wind through leaves (reverb)",
      "Flowers blooming (crystalline chimes)",
      "Vapor compression whoosh",
      "Glass crystallizing",
      "Final settling plink"
    ]
  },
  postProduction: {
    colorGrading: "Progression: Desaturated high-contrast deep black (shot 1) → Saturated prismatic (shot 2) → Pastel watercolor (shot 3) → Natural warm tones (shot 4-5). Bloom effect on lights. Subtle 16mm film grain for organic texture.",
    transitions: [
      "Match-cut (droplet surface → inside droplet)",
      "Cross-dissolve (prismatic realm → abstract garden)",
      "Fade (dissolving garden → converging vapor)",
      "Hard cut (materialization complete → macro liquid)",
      "Fade to black (final frame)"
    ],
    titling: [
      "'Essence' - Elegant serif font, integrated as luminous vapor",
      "'Où commence la mémoire' - Delicate subtitle, same vapor style",
      "No intrusive logo, everything organic to image"
    ]
  },
  estimatedCost: {
    analysis: 100,
    shotsGeneration: 170,
    total: 270
  }
};

// ============================================================================
// MOCK DATA SERVICE
// ============================================================================

/**
 * Get a mock concept based on keywords in the brief
 */
export function getMockConcept(description: string): VideoAnalysisResponse {
  const lowerDesc = description.toLowerCase();
  
  // Match keywords to appropriate mock concept
  if (lowerDesc.includes('orée') || lowerDesc.includes('oree') || lowerDesc.includes('bois')) {
    console.log('📦 Using mock concept: Orée - Roots of Concrete');
    return MOCK_OREE_ROOTS_CONCRETE;
  }
  
  if (lowerDesc.includes('essence') || lowerDesc.includes('memory') || lowerDesc.includes('mémoire')) {
    console.log('📦 Using mock concept: Essence - Memory Extraction');
    return MOCK_ESSENCE_MEMORY;
  }
  
  // Default to Orée concept if no match
  console.log('📦 Using default mock concept: Orée - Roots of Concrete');
  return MOCK_OREE_ROOTS_CONCRETE;
}

/**
 * Check if mock mode is enabled
 */
export function isMockModeEnabled(): boolean {
  // Check environment variable
  const envMock = Deno.env.get('USE_MOCK_VIDEO_ANALYSIS');
  if (envMock === 'true') {
    return true;
  }
  
  // Default to true for now (since no credits available)
  return true;
}
