/**
 * GOOGLE GEMINI VIA REPLICATE API SERVICE
 * Integration with Gemini via Replicate API
 */

import rateLimiter from './replicate-rate-limiter.ts';

// ============================================
// TYPES
// ============================================

interface GenerateTextParams {
  prompt: string;
  systemPrompt?: string;
  temperature?: number;
  maxTokens?: number;
}

interface GenerateTextResult {
  text: string;
}

// ============================================
// GEMINI VIA REPLICATE API
// ============================================

/**
 * Generate text using Google Gemini via Replicate API
 */
export async function generateTextNative(params: GenerateTextParams): Promise<GenerateTextResult> {
  const REPLICATE_API_KEY = Deno.env.get('REPLICATE_API_KEY');
  
  if (!REPLICATE_API_KEY) {
    console.error('❌ REPLICATE_API_KEY not found in environment');
    throw new Error('REPLICATE_API_KEY not configured');
  }
  
  // ✅ RATE LIMITING: Wait if necessary before making request
  const waitTime = await rateLimiter.waitAndRecord('gemini-text');
  if (waitTime > 0) {
    console.log(`⏳ [Rate Limit] Waited ${Math.ceil(waitTime / 1000)}s for rate limit`);
  }
  
  console.log('🤖 [Gemini Replicate] Calling Gemini 2.5 Flash via Replicate API...');
  console.log('📝 Prompt length:', params.prompt.length);
  console.log('🌡️ Temperature:', params.temperature || 0.7);
  
  try {
    // Use system_instruction parameter if provided (separate from prompt)
    const requestBody: any = {
      input: {
        prompt: params.prompt,
        temperature: params.temperature || 0.7,
        max_output_tokens: params.maxTokens || 65535, // ✅ Use maximum for long responses
        top_p: 0.95,
      },
    };
    
    // Add system_instruction if provided (Replicate's parameter for system prompts)
    if (params.systemPrompt) {
      requestBody.input.system_instruction = params.systemPrompt;
    }
    
    console.log('📤 Sending request to Replicate...');
    console.log('🔧 Request body:', JSON.stringify(requestBody).substring(0, 200) + '...');
    
    // Call Replicate API to create prediction
    const response = await fetch('https://api.replicate.com/v1/models/google/gemini-2.5-flash/predictions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${REPLICATE_API_KEY}`,
        'Content-Type': 'application/json',
        'Prefer': 'wait',
      },
      body: JSON.stringify(requestBody),
    });
    
    console.log('📥 Response status:', response.status, response.statusText);
    
    if (!response.ok) {
      const errorText = await response.text();
      console.error('❌ [Gemini Replicate] API error response:', errorText);
      throw new Error(`Replicate API error: ${response.status} ${response.statusText} - ${errorText}`);
    }
    
    const result = await response.json();
    console.log('📦 Prediction result:', JSON.stringify(result).substring(0, 200) + '...');
    
    // Check prediction status
    if (result.status === 'failed') {
      console.error('❌ Prediction failed:', result.error);
      throw new Error(`Prediction failed: ${result.error}`);
    }
    
    // If prediction is still processing, poll for result
    let prediction = result;
    if (prediction.status !== 'succeeded') {
      console.log('⏳ Prediction not complete, polling...');
      prediction = await pollPrediction(prediction.id, REPLICATE_API_KEY);
    }
    
    // Extract text from output
    const text = Array.isArray(prediction.output) 
      ? prediction.output.join('') 
      : prediction.output;
    
    if (!text) {
      console.error('❌ No text in output:', prediction.output);
      throw new Error('No text generated by Gemini');
    }
    
    console.log('✅ [Gemini Replicate] Text generated successfully');
    console.log(`📝 Response length: ${text.length} characters`);
    
    return { text };
    
  } catch (error) {
    console.error('❌ [Gemini Replicate] Error:', error);
    console.error('Stack trace:', error.stack);
    throw error;
  }
}

/**
 * Analyze images with Gemini Vision via Replicate
 */
export async function analyzeImagesNative(params: {
  imageUrls: string[];
  prompt: string;
  systemPrompt?: string;
  temperature?: number;
}): Promise<GenerateTextResult> {
  const REPLICATE_API_KEY = Deno.env.get('REPLICATE_API_KEY');
  
  if (!REPLICATE_API_KEY) {
    console.error('❌ REPLICATE_API_KEY not found in environment');
    throw new Error('REPLICATE_API_KEY not configured');
  }
  
  // ✅ RATE LIMITING: Wait if necessary before making request
  const waitTime = await rateLimiter.waitAndRecord('gemini-vision');
  if (waitTime > 0) {
    console.log(`⏳ [Rate Limit] Waited ${Math.ceil(waitTime / 1000)}s for rate limit`);
  }
  
  console.log(`👁️ [Gemini Vision Replicate] Analyzing ${params.imageUrls.length} images...`);
  console.log('🖼️ Image URLs:', params.imageUrls);
  
  try {
    // Combine system prompt and user prompt
    const fullPrompt = params.systemPrompt 
      ? `${params.systemPrompt}\n\n${params.prompt}`
      : params.prompt;
    
    if (params.imageUrls.length === 0) {
      console.error('❌ No image URLs provided');
      throw new Error('At least one image URL is required');
    }
    
    const requestBody = {
      input: {
        prompt: fullPrompt,
        // Pass image URLs - Gemini will fetch and analyze them
        images: params.imageUrls,
        temperature: params.temperature || 0.7,
        max_output_tokens: 65535, // ✅ Use maximum for long campaign responses
      },
    };
    
    console.log('📤 Sending vision request to Replicate...');
    console.log('🔧 Request body:', JSON.stringify(requestBody).substring(0, 300) + '...');
    
    // Call Replicate API to create prediction with images
    const response = await fetch('https://api.replicate.com/v1/models/google/gemini-2.5-flash/predictions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${REPLICATE_API_KEY}`,
        'Content-Type': 'application/json',
        'Prefer': 'wait',
      },
      body: JSON.stringify(requestBody),
    });
    
    console.log('📥 Vision response status:', response.status, response.statusText);
    
    if (!response.ok) {
      const errorText = await response.text();
      console.error('❌ [Gemini Vision Replicate] API error response:', errorText);
      throw new Error(`Replicate API error: ${response.status} ${response.statusText} - ${errorText}`);
    }
    
    const result = await response.json();
    console.log('📦 Vision prediction result:', JSON.stringify(result).substring(0, 200) + '...');
    
    // Check prediction status
    if (result.status === 'failed') {
      console.error('❌ Vision prediction failed:', result.error);
      throw new Error(`Prediction failed: ${result.error}`);
    }
    
    // If prediction is still processing, poll for result
    let prediction = result;
    if (prediction.status !== 'succeeded') {
      console.log('⏳ Vision prediction not complete, polling...');
      prediction = await pollPrediction(prediction.id, REPLICATE_API_KEY);
    }
    
    // Extract text from output
    const text = Array.isArray(prediction.output) 
      ? prediction.output.join('') 
      : prediction.output;
    
    if (!text) {
      console.error('❌ No text in vision output:', prediction.output);
      throw new Error('No text generated by Gemini Vision');
    }
    
    console.log('✅ [Gemini Vision Replicate] Analysis completed');
    console.log(`📝 Response length: ${text.length} characters`);
    
    return { text };
    
  } catch (error) {
    console.error('❌ [Gemini Vision Replicate] Error:', error);
    console.error('Stack trace:', error.stack);
    throw error;
  }
}

/**
 * Poll Replicate prediction until completion
 */
async function pollPrediction(predictionId: string, apiKey: string, maxAttempts: number = 60): Promise<any> {
  console.log(`🔄 Polling prediction: ${predictionId}`);
  
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    await new Promise(resolve => setTimeout(resolve, 1000)); // Wait 1 second
    
    console.log(`⏳ Polling attempt ${attempt + 1}/${maxAttempts}...`);
    
    const response = await fetch(`https://api.replicate.com/v1/predictions/${predictionId}`, {
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
    });
    
    if (!response.ok) {
      const errorText = await response.text();
      console.error('❌ Poll request failed:', errorText);
      throw new Error(`Failed to poll prediction: ${response.status} - ${errorText}`);
    }
    
    const prediction = await response.json();
    console.log(`📊 Status: ${prediction.status}`);
    
    if (prediction.status === 'succeeded') {
      console.log('✅ Prediction succeeded');
      return prediction;
    }
    
    if (prediction.status === 'failed') {
      console.error('❌ Prediction failed during polling:', prediction.error);
      throw new Error(`Prediction failed: ${prediction.error}`);
    }
    
    if (prediction.status === 'canceled') {
      console.error('❌ Prediction was canceled');
      throw new Error('Prediction was canceled');
    }
    
    console.log(`⏳ Attempt ${attempt + 1}/${maxAttempts}: ${prediction.status}`);
  }
  
  console.error('❌ Prediction timeout after', maxAttempts, 'attempts');
  throw new Error('Prediction timeout');
}

// ============================================
// EXPORT
// ============================================

export const geminiNative = {
  generateText: generateTextNative,
  analyzeImages: analyzeImagesNative,
};

console.log('✅ Gemini Replicate Service loaded');